# Generated by Django 2.0.2 on 2018-08-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypolls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('gender_type', models.CharField(max_length=200)),
                ('occupation_type', models.CharField(max_length=200)),
                ('counntry_text', models.CharField(max_length=200)),
            ],
        ),
    ]
